### ISSUE TITLE
Download/export of maps do not retain style.

### ISSUE THREAD

**Issue by damonsk** [damonsk/onlinewardleymaps#32]
when using 
`style handwritten` 
or 
`style wardley`
and downloading maps, the style is lost.

**Comment by ShaunBulbrook** [comment]
I've noticed that the fonts also drop here.
I might have a quick fix for this one will see if I can get it done before I leave the office tonight.

**Comment by ShaunBulbrook** [comment]
Hmm 
Sadly my quick fix was not to be. 

I need to do a bit of reading up on font family use in SVGs and re-check over the supported properties of html2canvas. 
I have a WIP branch that might nudge someone in the right direction in the interim. (This is very much experimental, the way the styles are applied in that branch are not at all maintainable!)
https://github.com/ShaunBulbrook/onlinewardleymaps/pull/1

^ In the example above the wardley style renders with the same font I see in the browser. (except for text-transform)  - No change to the hand-written font (Potentially because it is loaded from a 3rd party)

**Comment by damonsk** [comment]
had a look around - stumbled upon this: https://github.com/niklasvh/html2canvas/issues/1709#issuecomment-447798425

I've done a few inline with your draft to try and make it more maintainable.

**Comment by ShaunBulbrook** [comment]
Amazing! Shout if there's anything you need!

**Comment by ChristianDavis** [comment]
I think you can close this one
