### ISSUE TITLE
Only show lines of future when components evolve

### ISSUE THREAD

**Issue by jimdowning** [damonsk/onlinewardleymaps#7]
Drawing both lines of present and lines of the future makes the maps really cluttered. Could we ditch the lines of present when components evolve?

**Comment by ShaunBulbrook** [comment]
Not against this, but it this does become a thing, I'd prefer it to be behind a toggle. 

It looks like the map is doing a bit of this at the moment, took me a few minutes to work out what was happening when evolving things, not sure how a new user would experiance it. 

@jimdowning I've never really drawn maps with relationships only on evolutions - mainly because mine are mostly on paper and I draw evolutions as a secondary step - Is this a pattern you use often? (Just curious to see if I'm doing things wrong!)  😃

**Comment by jimdowning** [comment]
I think you're right - it needs flexibility to all the things folks do with maps. 

We'll usually create maps as a sequence, so we'll show the 'future only' state in the later diagrams. 
I think the handling of lines of future needs some thought. Perhaps it could be an attribute on the relationship? 
```
component Cup of Tea [0.8, 0.73]
component Hot Water [.6 .78] 
component Kettle [.3 .3] evolve .88
component Power [.1 .6] evolve .8
Cup of Tea -> Hot Water
Hot Water -> Kettle 
Kettle -> Power [hide-present]
```
OR
``` 
Kettle -> Power [future]
```
If the meaning was 'show' and the default was 'all'
To be honest, this kind of approach might be easier to remember for representing flow as well, and would allow further relationship customisation. 

Thinking about it, this would also be useful because sometimes the relationships of the future state are different to the present state, so being able to control the visibility of present and future lines would be useful.

**Comment by jimdowning** [comment]
Another thought of a suggested syntax how about the `-` before the `>` represents the past line and a `-` after denotes the future line, either being substituted by `+` to add flow highlighting? Not back compatible. Examples: -

```
Kettle >- Power (shows only line of the future)
Kettle ->- Power (shows both lines of future and past)
Kettle ->+ Power (shows both lines, with flow on the line of the future)
Kettle +>+ Power (shows both lines, with flow on both)
```

**Comment by damonsk** [comment]
This is behind a toggle from the more menu.
